{ pkgs, lib, ... }:
let
  isDarwin = pkgs.stdenv.isDarwin;
  configText = ''
    # Generated by Home Manager to match the iTerm2 profile feel.
    font-family = "FiraMono Nerd Font Mono"
    font-size = 11

    term = xterm-256color

    background = #2b2d2e
    foreground = #d2d8d9
    bold-color = #ececec
    selection-background = #e4e8ed
    selection-foreground = #3f4041
    cursor-color = #708284
    cursor-text = #002831

    palette = 0=#7d8b8f
    palette = 1=#b23a52
    palette = 2=#789b6a
    palette = 3=#b9ac4a
    palette = 4=#2a7fac
    palette = 5=#bd4f5a
    palette = 6=#44a799
    palette = 7=#d2d8d9
    palette = 8=#888888
    palette = 9=#f24840
    palette = 10=#80c470
    palette = 11=#ffeb62
    palette = 12=#4196ff
    palette = 13=#fc5275
    palette = 14=#53cdbd
    palette = 15=#d2d8d9

    # Control key bindings for ASCII control characters (Ctrl+2..8, Ctrl+-)
    keybind = ctrl+digit_2=text:\x00
    keybind = ctrl+digit_3=text:\x1b
    keybind = ctrl+digit_4=text:\x1c
    keybind = ctrl+digit_5=text:\x1d
    keybind = ctrl+digit_6=text:\x1e
    keybind = ctrl+digit_7=text:\x1f
    keybind = ctrl+digit_8=text:\x7f
    keybind = ctrl+-=text:\x1f

    # Arrow key bindings with modifiers to match iTerm2 behavior
    keybind = shift+arrow_up=text:\x1b[1;2A
    keybind = ctrl+arrow_up=text:\x1b[1;5A
    keybind = ctrl+shift+arrow_up=text:\x1b[1;6A
    keybind = alt+arrow_up=text:\x1b\x1b[A

    keybind = shift+arrow_down=text:\x1b[1;2B
    keybind = ctrl+arrow_down=text:\x1b[1;5B
    keybind = ctrl+shift+arrow_down=text:\x1b[1;6B
    keybind = alt+arrow_down=text:\x1b\x1b[B

    keybind = shift+arrow_left=text:\x1b[1;2D
    keybind = ctrl+arrow_left=text:\x1b[1;5D
    keybind = ctrl+shift+arrow_left=text:\x1b[1;6D
    keybind = alt+arrow_left=text:\x1b\x1b[D

    keybind = shift+arrow_right=text:\x1b[1;2C
    keybind = ctrl+arrow_right=text:\x1b[1;5C
    keybind = ctrl+shift+arrow_right=text:\x1b[1;6C
    keybind = alt+arrow_right=text:\x1b\x1b[C

    # Allow AeroSpace to handle Cmd+[1-9] workspace switching
    keybind = super+1=unbind
    keybind = super+2=unbind
    keybind = super+3=unbind
    keybind = super+4=unbind
    keybind = super+5=unbind
    keybind = super+6=unbind
    keybind = super+7=unbind
    keybind = super+8=unbind
    keybind = super+9=unbind
    keybind = super+digit_1=unbind
    keybind = super+digit_2=unbind
    keybind = super+digit_3=unbind
    keybind = super+digit_4=unbind
    keybind = super+digit_5=unbind
    keybind = super+digit_6=unbind
    keybind = super+digit_7=unbind
    keybind = super+digit_8=unbind
    keybind = super+digit_9=unbind

    # Match custom iTerm2 split navigation (Cmd+J / Cmd+K)
    keybind = super+j=goto_split:previous
    keybind = super+k=goto_split:next

    keybind = shift+home=text:\x1b[1;2H
    keybind = ctrl+home=text:\x1b[1;5H
    keybind = shift+end=text:\x1b[1;2F
    keybind = ctrl+end=text:\x1b[1;5F

    keybind = shift+f1=text:\x1b[1;2P
    keybind = shift+f2=text:\x1b[1;2Q
    keybind = shift+f3=text:\x1b[1;2R
    keybind = shift+f4=text:\x1b[1;2S
    keybind = shift+f5=text:\x1b[15;2~
    keybind = shift+f6=text:\x1b[17;2~
    keybind = shift+f7=text:\x1b[18;2~
    keybind = shift+f8=text:\x1b[19;2~
    keybind = shift+f9=text:\x1b[20;2~
    keybind = shift+f10=text:\x1b[21;2~
    keybind = shift+f11=text:\x1b[23;2~
    keybind = shift+f12=text:\x1b[24;2~
  '';
in
lib.mkIf isDarwin {
  home.packages = [ pkgs.ghostty-bin ];

  home.file."Library/Application Support/com.mitchellh.ghostty/config" = {
    text = configText;
  };
}
